using Microsoft.VisualStudio.Shell.Interop;
using System;
using System.Collections.Generic;

namespace MyExtension
{
    public enum ToolWindowType
    {
        Unknown,

        Toolbox,
        PropertyBrowser,
        SolutionExplorer,
        OutputWindow,
        DocumentOutline,
        TaskList,
        ServerExplorer,
        MacroExplorer,
        ContextWindow,
        ClassView,
        ResourceView,
        ObjectSearchWindow,
        CommandWindow,
        ObjectSearchResultsWindow,
        ObjectBrowser,
        BrowserDoc,
        FindReplace,
        FindAdvanced,
        FindResults1,
        FindResults2,

        Autos,
        BookmarkWindow,
        Breakpoints,
        CallBrowserWindow,
        CallBrowserSecondaryWindow,
        CallStack,
        ClassDetails,
        CodeDefinitionWindow,
        ConsoleIO,
        DataSourceWindow,
        DefinitionWindow,
        Disassembly,
        ErrorList,
        HelpFavorites,
        HelpHowDoI,
        HelpIndex,
        HelpIndexResults,
        HelpSearch,
        ImmediateWindow,
        LocalChanges,
        Locals,
        Memory,
        Modules,
        ObjectTestBench,
        PortDetails,
        Processes,
        PropertySheetManager,
        Registers,
        RunningDocuments,
        SdmDesignerTransactions,
        SettingsAndConstraints,
        StartPage,
        StyleOrganizerToolWindow,
        SystemView,
        TableOfContents,
        Threads,
        TrinityDataWindow,
        UAMSynchronizations,
        VCColorPalette,
        VCPropertyManager,
        Watch,
        WebBrowserPreviewWindow,
        WebBrowserWindow
    }

    public static class ToolWindowTypeResolver
    {
        private static readonly Dictionary<Guid, ToolWindowType> Map =
            new()
            {
                [new Guid(ToolWindowGuids80.Toolbox)] = ToolWindowType.Toolbox,
                [new Guid(ToolWindowGuids80.PropertiesWindow)] = ToolWindowType.PropertyBrowser,
                [new Guid(ToolWindowGuids80.SolutionExplorer)] = ToolWindowType.SolutionExplorer,
                [new Guid(ToolWindowGuids80.Outputwindow)] = ToolWindowType.OutputWindow,
                [new Guid(ToolWindowGuids80.DocumentOutline)] = ToolWindowType.DocumentOutline,
                [new Guid(ToolWindowGuids80.TaskList)] = ToolWindowType.TaskList,
                [new Guid(ToolWindowGuids80.ServerExplorer)] = ToolWindowType.ServerExplorer,
                [new Guid(ToolWindowGuids80.MacroExplorer)] = ToolWindowType.MacroExplorer,
                [new Guid(ToolWindowGuids80.ContextWindow)] = ToolWindowType.ContextWindow,
                [new Guid(ToolWindowGuids80.ClassView)] = ToolWindowType.ClassView,
                [new Guid(ToolWindowGuids80.ResourceView)] = ToolWindowType.ResourceView,
                [new Guid(ToolWindowGuids80.ObjectSearchWindow)] = ToolWindowType.ObjectSearchWindow,
                [new Guid(ToolWindowGuids80.CommandWindow)] = ToolWindowType.CommandWindow,
                [new Guid(ToolWindowGuids80.ObjectSearchResultsWindow)] = ToolWindowType.ObjectSearchResultsWindow,
                [new Guid(ToolWindowGuids80.ObjectBrowser)] = ToolWindowType.ObjectBrowser,
                [new Guid(ToolWindowGuids80.BrowserDoc)] = ToolWindowType.BrowserDoc,
                [new Guid(ToolWindowGuids80.FindReplace)] = ToolWindowType.FindReplace,
                [new Guid(ToolWindowGuids80.FindAdvanced)] = ToolWindowType.FindAdvanced,
                [new Guid(ToolWindowGuids80.Find1)] = ToolWindowType.FindResults1,
                [new Guid(ToolWindowGuids80.Find2)] = ToolWindowType.FindResults2,

                [new Guid(ToolWindowGuids80.Autos)] = ToolWindowType.Autos,
                [new Guid(ToolWindowGuids80.BookmarkWindow)] = ToolWindowType.BookmarkWindow,
                [new Guid(ToolWindowGuids80.Breakpoints)] = ToolWindowType.Breakpoints,
                [new Guid(ToolWindowGuids80.CallBrowserWindow)] = ToolWindowType.CallBrowserWindow,
                [new Guid(ToolWindowGuids80.CallBrowserSecondaryWindow)] = ToolWindowType.CallBrowserSecondaryWindow,
                [new Guid(ToolWindowGuids80.CallStack)] = ToolWindowType.CallStack,
                [new Guid(ToolWindowGuids80.ClassDetails)] = ToolWindowType.ClassDetails,
                [new Guid(ToolWindowGuids80.CodedefinitionWindow)] = ToolWindowType.CodeDefinitionWindow,
                [new Guid(ToolWindowGuids80.ConsoleIO)] = ToolWindowType.ConsoleIO,
                [new Guid(ToolWindowGuids80.DataSourceWindow)] = ToolWindowType.DataSourceWindow,
                [new Guid(ToolWindowGuids80.DefinitionWindow)] = ToolWindowType.DefinitionWindow,
                [new Guid(ToolWindowGuids80.Disassembly)] = ToolWindowType.Disassembly,
                [new Guid(ToolWindowGuids80.ErrorList)] = ToolWindowType.ErrorList,
                [new Guid(ToolWindowGuids80.HelpFavorites)] = ToolWindowType.HelpFavorites,
                [new Guid(ToolWindowGuids80.HelpHowDoI)] = ToolWindowType.HelpHowDoI,
                [new Guid(ToolWindowGuids80.Helpindex)] = ToolWindowType.HelpIndex,
                [new Guid(ToolWindowGuids80.HelpIndexResults)] = ToolWindowType.HelpIndexResults,
                [new Guid(ToolWindowGuids80.HelpSearch)] = ToolWindowType.HelpSearch,
                [new Guid(ToolWindowGuids80.ImmediateWindow)] = ToolWindowType.ImmediateWindow,
                [new Guid(ToolWindowGuids80.LocalChanges)] = ToolWindowType.LocalChanges,
                [new Guid(ToolWindowGuids80.Locals)] = ToolWindowType.Locals,
                [new Guid(ToolWindowGuids80.Memory)] = ToolWindowType.Memory,
                [new Guid(ToolWindowGuids80.Modules)] = ToolWindowType.Modules,
                [new Guid(ToolWindowGuids80.ObjectTestBench)] = ToolWindowType.ObjectTestBench,
                [new Guid(ToolWindowGuids80.PortDetails)] = ToolWindowType.PortDetails,
                [new Guid(ToolWindowGuids80.Processes)] = ToolWindowType.Processes,
                [new Guid(ToolWindowGuids80.PropertySheetManager)] = ToolWindowType.PropertySheetManager,
                [new Guid(ToolWindowGuids80.Registers)] = ToolWindowType.Registers,
                [new Guid(ToolWindowGuids80.RunningDocuments)] = ToolWindowType.RunningDocuments,
                [new Guid(ToolWindowGuids80.SdmDesignerTransactions)] = ToolWindowType.SdmDesignerTransactions,
                [new Guid(ToolWindowGuids80.SettingsandConstraints)] = ToolWindowType.SettingsAndConstraints,
                [new Guid(ToolWindowGuids80.StartPage)] = ToolWindowType.StartPage,
                [new Guid(ToolWindowGuids80.StyleOrganizerToolWindow)] = ToolWindowType.StyleOrganizerToolWindow,
                [new Guid(ToolWindowGuids80.SystemView)] = ToolWindowType.SystemView,
                [new Guid(ToolWindowGuids80.Tableofcontents)] = ToolWindowType.TableOfContents,
                [new Guid(ToolWindowGuids80.Threads)] = ToolWindowType.Threads,
                [new Guid(ToolWindowGuids80.TrinityDataWindow)] = ToolWindowType.TrinityDataWindow,
                [new Guid(ToolWindowGuids80.UAMSynchronizations)] = ToolWindowType.UAMSynchronizations,
                [new Guid(ToolWindowGuids80.VCColorPalette)] = ToolWindowType.VCColorPalette,
                [new Guid(ToolWindowGuids80.VCPropertyManager)] = ToolWindowType.VCPropertyManager,
                [new Guid(ToolWindowGuids80.Watch)] = ToolWindowType.Watch,
                [new Guid(ToolWindowGuids80.WebBrowserPreviewWindow)] = ToolWindowType.WebBrowserPreviewWindow,
                [new Guid(ToolWindowGuids80.WebBrowserWindow)] = ToolWindowType.WebBrowserWindow,
            };

        public static ToolWindowType FromGuid(Guid guid)
        {
            return Map.TryGetValue(guid, out var kind)
                ? kind
                : ToolWindowType.Unknown;
        }
    }
}